on: ["push", "pull_request"]

name: Node CI

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: npm install, make test-coverage
      run: |
        npm install
        npm run codecov-coverage
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        # file: ./coverage.xml #optional
        # flags: unittests #optional
        # name: codecov-umbrella #optional
        # yml: ./codecov.yml #optional
